language: java
jdk: oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test
deploy:
  provider: heroku
  app: a-spring-app
  api_key:
    secure: ftKKM0H5U75QM4rcAzXTpXt/y+kWTdPIxCkvXLbxwRnAbGoabr+j1VNveyumFWyto3OPTMghcbc1u8Pj6/wxTPYTmhetHOdgj+eU5a7TsSs6ntOyMeM5WL3aY1yMr+JSSihCquiMCcMM1rarGaZlUuwLHgkaqtgCfQoDEQknFFtvn7Jc5ry453I2QsH41vxpmjA0MGxvyKY8GGVkPz0w0SAQ/jrEYW1pvD9Gh0goNshJlaht1oY9TkzrYP61WDO4wfwEJcrEj2q4HQEGmjv7ZaX8uOBTArV12d8Us/T9MIuqH0AlLAHmejCo3FOsmLzxrrAytvKKL0ZOjEO3RwBzA7RTotE3G+d8Aq+vFD9k/eUmU1xPt42+1HznDh5O6lguLdazphwR7FBu8QFIPuzbnoQ4S+pG2nAV/09cCSTnOFAiQN4s1+FzPWpfKPebImMa6MNftobHbcKWjzNRJwnb2RFsY4/yCbnHKC3maczQA/DL5iLL2UJw+FYk+L0GHMfr+PqsN9gT+ZY1PGImVw10xs7hR6yHSVDSdyTnRlVo0BdzTxAJJvCWra8XZHhpZQXvBjgje3DeSYPKKSN29JgVQBpGHJEq/llSY/Kjqrar/6exm2BcPbFmZd2+RZLPDBFgw4Y1is/xW5NEwxcP6fb7sZLmmLf07xZGMuCkgvhFjJw=
